config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/home', to: 'pages#home'
  resources :events
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :notes, presence: true, length: { minimum: 5, maximum: 300 }
  validates :status, presence: true,
            numericality: { only_integer: true },
            length: { maximum: 1 }
  STATUS_LIST = { "Not Started" => 1, "In Progress" => 2, "Missing" => 3, "Unavailable" => 4, "Completed" => 5, "Action Needed" => 6 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  before_save { self.email = email.downcase }
  has_many :events, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true,
            length: { minimum: 5, maximum: 30 }
  validates :email, presence: true,
            length: { minimum: 5, maximum: 100 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  PIC_LIST = { "Male" => 1, "Female" => 2 }

  private
    def picture_size
      if picture.size > 10.megabytes
        errors.add(:picture, "should be less than 10 MB. Current pic size is: #{picture.size}")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.user = User.find(1)

    if @event.save
      flash[:success] = "Your EVENT was CREATED successfully!"
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:success] = "Your EVENT was UPDATED successfully!"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def show
    @event = Event.find(params[:id])
    @status = event_status_translator(@event.status)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

private
  def event_params
    params.require(:event).permit(:title, :notes, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(users_params)

    if @user.save
      flash[:success] = "Your USER was CREATED successfully!"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      flash[:success] = "Your USER was UPDATED successfully!"
      redirect_to users_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def users_params
    params.require(:user).permit(:username, :email, :default_pic, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_status_translator(event)
    case event
      when 1
        "Not Started"
      when 2
        "In Progress"
      when 3
        "Missing"
      when 4
        "Unavailable"
      when 5
        "Completed"
      when 6
        "Action Needed"
      else "Something looks wrong"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= render 'shared/errors', obj: @event %>

    <%= form_for @event do |e| %>
    <p>
      <%= e.label :title %><br>
      <%= e.text_field :title %>
    </p>

    <p>
      <%= e.label :notes %><br>
      <%= e.text_area :notes %>
    </p>

    <p>
      <%= e.label :status %><br>
      <%= e.select(:status, Event::STATUS_LIST) %>
    </p>
    <br>

    <p><%= e.submit( @event.new_record? ? "Save EVENT": "Update EVENT", class: "btn btn-success")  %></p>
    <% end %>
    <br>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'shared/page_title', title: "Edit EVENT" %>

<%= render 'form' %>
<%= link_to 'Back', events_path, class: "btn btn-success" %>

app/views/events/index.html.erb
<%
  def event_status_translator(event)
     case event
     when 1
     "Not Started"
     when 2
     "In Progress"
     when 3
     "Missing"
     when 4
     "Unavailable"
     when 5
     "Completed"
     when 6
     "Action Needed"
     else "Something looks wrong"
     end
 end %>

<%= render 'shared/page_title', title: "Timeline" %>

<%= link_to 'New Event', new_event_path, class: "btn btn-success" %>
<table>
  <tr>
    <th>Title</th>
    <th>Notes</th>
    <th>Status</th>
    <th colspan="2"></th>
  </tr>
  <% @event.each do |e| %>
    <tr>
      <td><%= e.title %></td>
      <td><%= e.notes %></td>
      <td><%= event_status_translator(e.status) %></td>
      <td><%= link_to 'Show', event_path(e) %></td>
      <td><%= link_to 'Edit', edit_event_path(e) %></td>
      <td><%= link_to 'Destroy', event_path(e),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<%= render 'shared/page_title', title: "New EVENT" %>

<%= render 'form' %>
<p><%= link_to 'Cancel', events_path, class: "btn btn-warning btn-danger" %></p>

app/views/events/show.html.erb
<%= render 'shared/page_title', title: @event.title %>

<div class="row">
  <div class="col-md-10">
    <%= link_to "Edit EVENT", edit_event_path(@event), class: "btn btn-warning pull-right"%>
  </div>
</div>
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <p>
      <strong>User:</strong>
      <%= link_to "#{@event.user.username}", user_path(@event.user)  %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @event.title %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= @event.notes %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @status %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-warning" %>  |
<%= link_to 'Go Back to Timeline', events_path, class: "btn btn-success"%>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message|%>
      <div class="alert alert-<%= message_type %>">
        <%= message %><a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Case Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        <%= link_to "Timeline", events_path , class: "btn btn-lg btn-success", id: "logo" %>
        <div class="nav_item">
          <%= link_to "link1", "", class: "btn btn-default btn-success" %>
        </div>
        <div class="nav_item">
          <%= link_to "link2", "", class: "btn btn-default btn-success" %>
        </div>
        <div class="nav_item">
          <%= link_to "link3", "", class: "btn btn-default btn-success" %>
        </div>

        <div class="nav_item">
          <%= link_to "See all Users", users_path, class: "btn btn-default btn-success" %>
        </div>
      </div>
    </header>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
      <div class="container">
        <div class="footer">
          <p>&copy; Sakhniuk Immigration Law 2018</p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to My Case Manager</h1>
  <h2>
    This is the home page
  </h2>
  <%= link_to "See My Timeline", "", class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">Pay now</h3>
    <h2 clas="left">Browse and view recipes as guest</h2>
    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
  </div>

  <div class="col-lg-4">
    <h3 class="midrow">Contact Attorney</h3>
    <h2 clas="left">Browse and view recipes as guest</h2>
    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
  </div>

  <div class="col-lg-4">
    <h3 class="midrow">Something Else</h3>
    <h2 clas="left">Browse and view recipes as guest</h2>
    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
  </div>
</div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>
        <%= pluralize(obj.errors.count, "error") %> prohibited
        this event from being saved:
      </h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr>
</p>

app/views/users/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= render 'shared/errors', obj: @user %>

    <%= form_for(@user, html: { multipart: true }) do |u| %>
      <%= u.label :default_pic %><br>
      <%= u.select(:default_pic, User::PIC_LIST) %>
      <p>
      <%= u.label :username %><br>
      <%= u.text_field :username %>
      </p>
      <p>
      <%= u.label :email %><br>
      <%= u.text_field :email %>
      </p>
      <p>
        <label>Picture</label>
      </p>
      <span class="picture">
        <%= u.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: "custom-input" %>
      </span>
      <br>

      <p><%= u.submit( @user.new_record? ? "Create USER": "Update USER", class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#user_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 10){
        alert('Maximum size is 10MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/edit.html.erb
<%= render 'shared/page_title', title: 'Edit USER' %>

<%= render 'form' %>
<%= link_to 'Back to Users', users_path, class: "btn btn-success" %>

app/views/users/index.html.erb
<%= render 'shared/page_title', title: 'All Users' %>

<%= link_to 'New User', new_user_path, class: "btn btn-success center" %>
<br>
<br>

<%= will_paginate %>
<% @users.each do |u| %>
  <div class="row">
    <div class="col-md-2">
      <section class="user_info center">
        <% unless u.picture? %>
          <% if u.default_pic == 1 %>
            <div class="male"></div>
          <% elsif u.default_pic == 2 %>
            <div class="female"></div>
          <% end %>
        <% else %>
            <%= link_to user_path(u) do%>
                <%= image_tag(u.picture.url, class:"pic") if u.picture? %>
            <% end %>
        <% end %>

        <h5>Name: <%= u.username %></h5>
      </section>
    </div>

    <div class="col-lg-8 well">
      <%= link_to "Edit USER", edit_user_path(u), class: "btn btn-warning pull-right"%>
      <h4><%= link_to u.username, user_path(u) %></h4>
      <p><%= u.email %></p>
      <p><span class="quiet'"><%= time_ago_in_words(u.created_at) %></span></p>
    </div>
  </div>
  <hr/>
<% end %>
<%= will_paginate %>

app/views/users/new.html.erb
<%= render 'shared/page_title', title: 'Create NEW USER' %>


<%= render 'form' %>
<p><%= link_to 'Cancel', users_path, class: "btn btn-warning btn-danger" %></p>

app/views/users/show.html.erb
<%= render 'shared/page_title', title: @user.username %>
<div class="row">
  <div class="col-md-12">
    <%= link_to "Edit this USER", edit_user_path(@user), class: "btn btn-warning pull-right"%>
  </div>
  <br>
  <br>
</div>
<div class="row">
  <div class="well col-md-2">
    <% unless @user.picture? %>
      <% if @user.default_pic == 1 %>
        <div class="male"></div>
      <% elsif @user.default_pic == 2 %>
        <div class="female"></div>
      <% else %>
        <p>Something went wrong</p>
      <% end %>
    <% else %>
      <%=image_tag(@user.picture.url, class:"pic-show") if @user.picture? %>
    <% end %>
  </div>
  <div class="col-md-10">
    <div class="well">
      <p><strong>Email: </strong><%= @user.email %></p>
    </div>
  </div>
</div>

<h5><%= link_to "Return to all Users", users_path, class: "btn btn-success btn-small" %></h5>